k8s_yaml(local('kustomize build manifests'))
local_resource('nats-deploy', 'kubectl delete statefulset nats && kubectl apply -k manifests', deps="manifests", labels=['nats'])

k8s_resource('nats', labels=['nats'])
k8s_resource('nats-box', labels=['nats'])

