apiVersion: apps/v1
kind: Deployment
metadata:
  name: claio-kine
  namespace: claio-system
  labels:
    app: kine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kine
  template:
    metadata:
      labels:
        app: kine
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      - name: kine
        image: rancher/kine:v0.13.2
        env:
          - name: MARIADB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: claio-kine-mariadb
                key: root-password
        args:
          - --endpoint 
          - "mysql://root:${MARIADB_ROOT_PASSWORD}@tcp(claio-kine-mariadb:3306)/kine"
          - --ca-file
          - /etc/kine/secrets/ca.crt
          - --cert-file
          - /etc/kine/secrets/server.crt
          - --key-file
          - /etc/kine/secrets/server.key
        volumeMounts:
          - name: mariadb
            mountPath: /etc/kine/secrets
            readOnly: true
      volumes:
        - name: mariadb
          secret:
            secretName: claio-kine-mariadb  
---
apiVersion: v1
kind: Service
metadata:
  name: claio-kine
  namespace: claio-system
spec:
  selector:
    app.kubernetes.io/name: claio-kine
  ports:
    - name: kine
      port: 2379
      protocol: TCP