if os.path.exists('secrets.yaml') == False:
    local('./secrets/generate-secrets.sh')

local_resource('kine-secrets', './secrets/generate-secrets.sh', deps=['secrets'], labels=['kine'])

k8s_yaml(['kine.yaml', 'mariadb.yaml', 'secrets.yaml'])
k8s_resource('claio-kine-mariadb', port_forwards="3306", labels=['kine'])
k8s_resource('claio-kine', port_forwards="2379", labels=['kine'])

