k8s_yaml(['kine.yaml'])
k8s_resource('claio-kine', port_forwards="2379", labels=['kine'])
#k8s_resource('claio-kine-2', port_forwards="2380", labels=['kine'])

# --- tests ------------------------------

local_resource('kine-tests', 'tests/tests.sh', deps=["tests"], labels=['kine'], resource_deps=['claio-kine'])

