apiVersion: claio.github.com/v1alpha1
kind: ControlPlane
metadata:
  labels:
    app.kubernetes.io/name: claio
    app.kubernetes.io/managed-by: kustomize
  name: controlplane-sample
spec:
  version: 1.31.1
  