k8s_yaml(["namespace.yaml", "controlplane.yaml"])
k8s_resource(
    objects=['claio:ControlPlane:tenant-sample'],
    new_name="tenant-sample",
    port_forwards="6543", 
    labels=["Cluster-SAMPLE"])
