k8s_yaml(["namespace.yaml", "controlplane.yaml"])
k8s_resource(
    objects=['claio:ControlPlane:tenant-sample'],
    new_name="tenant-sample",
    port_forwards=['0.0.0.0:6543:6543'],
    resource_deps=['nats'],
    labels=["Cluster-SAMPLE"])
