#!/bin/bash

set -e

mkdir -p ~/.kube/tenants

if [ ! -z "$1" ]; then
	query="-1 -q $1"
fi

tenantns=$(kubectl --context=kind-claio get ns | egrep "^(tenant-|workload-)" | awk '{ print $1 }' | fzf $query)

if [ -z "$tenantns" ]; then
	echo "No tenant selected"
	exit 1
fi

tenant=${tenantns#tenant-}

# check if tenants kubeconfig secret exists
secret=$(kubectl --context=kind-claio get secrets --no-headers=true --ignore-not-found -n "$tenantns" "kubeconfig-admin")
if [ -z "$secret" ]; then
	echo "No admin kubeconfig secret found for tenant: $tenant"
	exit 1
fi

# get tenants kubeconfig
kubectl --context=kind-claio get secrets -n "$tenantns" "kubeconfig-admin" -o json |
	jq -r '.data["admin.conf"]' |
	base64 --decode |
	sed 's/cloud.at.inside:.*/cloud.at.inside/' \
		>~/.kube/tenants/${tenantns}.kubeconfig

export KUBECONFIG=~/.kube/tenants/${tenantns}.kubeconfig
kubectx "admin@tenant-dev"
kubens default

bash
