apiVersion: v1
kind: Pod
metadata:
  name: test
  labels:
    claio: control-plane
  namespace: default
spec:
  containers:
    - name: kube-apiserver
      image: registry.k8s.io/kube-apiserver:v1.29.1
      command:
        - kube-apiserver
      args:      
      - --advertise-address=1.1.1.1
      - --allow-privileged=true
      - --authorization-mode=Node,RBAC
      - --client-ca-file=/etc/kubernetes/pki/ca.crt
      - --enable-bootstrap-token-auth=true
      - --etcd-prefix=/test
      - --etcd-servers=http://claio-kine.claio-system.svc:2379
      - --external-hostname=test.kind-claio
      - --kubelet-client-certificate=/etc/kubernetes/pki/apiserver-kubelet-client.crt
      - --kubelet-client-key=/etc/kubernetes/pki/apiserver-kubelet-client.key
      - --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname
      - --proxy-client-cert-file=/etc/kubernetes/pki/front-proxy-client.crt
      - --proxy-client-key-file=/etc/kubernetes/pki/front-proxy-client.key
      - --requestheader-allowed-names=front-proxy-client
      - --requestheader-client-ca-file=/etc/kubernetes/pki/front-proxy-ca.crt
      - --requestheader-extra-headers-prefix=X-Remote-Extra-
      - --requestheader-group-headers=X-Remote-Group
      - --requestheader-username-headers=X-Remote-User
      - --secure-port=6443
      - --service-account-issuer=https://kubernetes.default.svc.cluster.local
      - --service-account-key-file=/etc/kubernetes/pki/sa.pub
      - --service-account-signing-key-file=/etc/kubernetes/pki/sa.key
      - --service-cluster-ip-range=192.168.128.0/17
      - --tls-cert-file=/etc/kubernetes/pki/apiserver.crt
      - --tls-private-key-file=/etc/kubernetes/pki/apiserver.key        
      imagePullPolicy: Always
      livenessProbe:
        failureThreshold: 3
        httpGet:
          path: /livez
          port: 6443
          scheme: HTTPS
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 1
      readinessProbe:
        failureThreshold: 3
        httpGet:
          path: /readyz
          port: 6443
          scheme: HTTPS
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 1
      resources:
        requests:
          cpu: 125m
          memory: 512Mi
      startupProbe:
        failureThreshold: 3
        httpGet:
          path: /livez
          port: 6443
          scheme: HTTPS
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 1
      volumeMounts:
      - mountPath: /etc/kubernetes/pki
        name: kubernetes-pki
        readOnly: true
  volumes:
    - name: kubernetes-pki
      projected:
        sources:
          - secret:
              name: ca
          - secret:
              name: apiserver
          - secret:
              name: apiserver-kubelet-client
          - secret:
              name: front-proxy-ca
          - secret:
              name: front-proxy-client
          - secret:
              name: sa

