apiVersion: v1
kind: Secret
metadata:
  labels:
    app: nats
  name: nats
  namespace: claio-system
stringData:
  nats.conf: |
    {
      "cluster": {
        "name": "nats",
        "no_advertise": true,
        "port": 6222,
        "routes": [
          "nats://nats-0.nats-headless:6222",
          "nats://nats-1.nats-headless:6222",
          "nats://nats-2.nats-headless:6222"
        ]
      },
      "http_port": 8222,
      "jetstream": {
        "max_file_store": 10Gi,
        "max_memory_store": 0,
        "store_dir": "/data"
      },
      "lame_duck_duration": "30s",
      "lame_duck_grace_period": "10s",
      "pid_file": "/var/run/nats/nats.pid",
      "port": 4222,
      "server_name": $SERVER_NAME
      "authorization": {
        "token": "ezQOdkulJeOmXfPRboo0"
      }
    }
  nats-box.conf: |
    {
      "url": "nats://ezQOdkulJeOmXfPRboo0@nats"
    }
