apiVersion: v1
kind: Service
metadata:
  labels:
    app: nats
  name: nats-headless
  namespace: claio-system
spec:
  clusterIP: None
  ports:
  - appProtocol: tcp
    name: nats
    port: 4222
    targetPort: nats
  - appProtocol: tcp
    name: cluster
    port: 6222
    targetPort: cluster
  - appProtocol: http
    name: monitor
    port: 8222
    targetPort: monitor
  publishNotReadyAddresses: true
  selector:
    app: nats
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nats
  name: nats
  namespace: claio-system
spec:
  ports:
  - appProtocol: tcp
    name: nats
    port: 4222
    targetPort: nats
  selector:
    app: nats
