apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kubeadm:kube-proxy
  namespace: kube-system
rules:
- apiGroups:
    - ""
  resourceNames:
    - kube-proxy
  resources:
    - configmaps
  verbs:
    - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kubeadm:kube-proxy
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kubeadm:kube-proxy
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: system:bootstrappers:kubeadm:default-node-token
